package com.vollmed.api.domain.doctor;

public enum DoctorSpecialties {
    CARDIOLOGIA,
    PEDIATRIA,
    ORTOPEDIA,
    DERMATOLOGIA,
    NEUROLOGIA,
    GINECOLOGIA,
    PSIQUIATRIA,
    ONCOLOGIA,
    ENDCRINOLOGIA,
    GASTROENTEROLOGIA,
    UROLOGIA,
    OTORRINOLARINGOLOGIA,
    PNEUMOLOGIA,
    REUMATOLOGIA,
    MEDICINA_FAMILIAR,
    ANESTESIOLOGIA,
    RADIOLOGIA,
    CIRURGIA_GERAL,
    CIRURGIA_PLASTICA,
    MEDICINA_DO_TRABALHO
}
